source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Trail_Example', :exclusive => true do
  pod 'Trail', :path => '../'
end

target 'Trail_Tests', :exclusive => true do
  pod 'Trail', :path => '../'

  pod 'Quick', '0.8.0'
  pod 'Nimble', '3.0.0'
end
